services:
  krstenica_database:
    image: postgres:16-alpine
    container_name: krstenica-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=krstenica
    ports:
      - "5560:5432"
    volumes:
      - krstenica-db:/var/lib/postgresql/data
    networks:
      - global
    
  krstenica-svc:
    image: krstenica-svc
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8011:8011"
    depends_on:
      - krstenica_database
    restart: on-failure
    networks:
      - global
    volumes:
      - ./config:/app/config
  
volumes:
  krstenica-db:
networks:
  global: