services:
  krstenica_database:
    image: postgres:16-alpine
    container_name: krstenica_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=krstenica
    ports:
        - "5560:5432"
    volumes:
      - krstenica_db:/var/lib/postgresql/data/
      - ./init_db:/docker-entrypoint-initdb.d
  
volumes:
  krstenica_db: 