db:
  # for starting outside of docker use first one
  # url: postgresql://admin:secret@localhost:5560/krstenica?sslmode=disable

  # for starting outside of docker use second one
  # url: postgresql://admin:secret@krstenica-db:5432/krstenica?sslmode=disable
  url: postgresql://admin:secret@localhost:5560/krstenica?sslmode=disable
  maxidletime: 1h
  maxlifetime: 1h
  maxopenconn: 100
  maxidleconn: 10

http_port: ":8001"

migration:
  direction: "up"
  version: 0

jwt_secret: "krstenica-backend-secret"
admin_jwt_secret: "krstenica-backend-secret"